name = "Myrovh's Modpack (forge)"
author = "myrovh"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f101fbae03436b6b9a2b5b9a53f6dc27cbde869c801ca68dc6de785ad3a1a8d5"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
