name = "Myrovh's Modpack (forge)"
author = "myrovh"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63020c06b5216e5eacd0c1ad8a78de9e34e44189fc2702908ae84bc86f2e068c"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
