name = "Myrovh's Modpack (forge)"
author = "myrovh"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63457175512e06171de2cf60c3da16f9161aaa2d14e27692c8c113e1cd55d2c6"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"
